### ISSUE TITLE
[New Feature] Anime Command

### ISSUE THREAD

**Issue by sr229** [owo-dev-team/owo-whats-this#7]
**Functions**
- [ ] able to search the percise Anime from keyword
- ~~has a async function if query is taking long~~ express solves that lmao

**Implementation**
- [ ] MAL Integration
- [ ] a extensible command module

**Comment by SunDwarf** [comment]
petition to make command name `generic weeb command`

**Comment by sr229** [comment]
Fixed on refactor. Closed.
